### PR TITLE
/UI : Improved UI of EditProfile full page,create blog page.

### PR DESCRIPTION
**Pull request by Ayush5071**
### Description

This pull request implements UI improvements for the blog submission form, including:

- Updated background to a softer white and gray color scheme.
- Enhanced placeholder styles for better visibility.
- Consistent padding and full-width layout for all form elements.
- Added mild shadows to inputs and the form.
- Removed hover effects from buttons.

These changes aim to enhance usability and provide a more professional interface.

## Type of change

- [x] Bug fix
- [x] New feature

## Motivation and Context

These enhancements improve the user experience during the blog submission process.

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/2d9eca8d-1447-4aeb-b0a7-ef0edaa66e6b

## Checklist:

- [x] I have registered at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the project style.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Ayush5071** [comment]
@Codipk  ma'am this issue is expired from active issue section ,also i,m not able to request again for the same.

**Comment by Codipk** [comment]
That's why I told u to request for approval within that time . Contact  abhishek sir

**Comment by Ayush5071** [comment]
Okay mam i informed Abhishek sir

**Comment by Codipk** [comment]
@Ayush5071 send the approval req

**Comment by Ayush5071** [comment]
@Codipk  done mam ThankYou

**Pull request merged**
